image:
  repository: my-fastapi-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000     

env:

  DB_HOST: "postgresql.infra.svc.cluster.local"
  DB_PORT: "5432"

  KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.infra.svc.cluster.local:9092"