postgresql:
  image:
    tag: "16" 
  architecture: standalone
  auth:
    postgresPassword: "password"
    database: "appdb"
  primary:
    persistence:
      enabled: false

mongodb:
  image:
    tag: "7.0"
  architecture: standalone
  auth:
    rootPassword: "password"
  persistence:
    enabled: false

redis:
  image:
    tag: "7.2"
  architecture: standalone
  auth:
    password: "password"
  master:
    persistence:
      enabled: false

strimzi-kafka-operator: {}

ingress-nginx:
  controller:
    service:
      type: LoadBalancer