apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-server
                port:
                  number: 8080
          
          - path: /fastapi
            pathType: Prefix
            backend:
              service:
                name: fastapi-server
                port:
                  number: 8000